export const REQUEST_CONTENT = 'REQUEST_CONTENT';
export const RECEIVE_CONTENT = 'RECEIVE_CONTENT';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
export const CLEAR_LOGIN = 'CLEAR_LOGIN';

export const REQUEST_SAVEVIEWERSCOUNT = 'REQUEST_SAVEVIEWERSCOUNT';
export const RECEIVE_SAVEVIEWERSCOUNT = 'RECEIVE_SAVEVIEWERSCOUNT';
